"""empty message

Revision ID: a201fea6410d
Revises: 
Create Date: 2022-03-09 14:08:45.332154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a201fea6410d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center',
    sa.Column('center_id', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('adress', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('center_id'),
    sa.UniqueConstraint('center_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specie',
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('specie_name', sa.String(length=100), nullable=False),
    sa.Column('short_desc', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('specie_id'),
    sa.UniqueConstraint('specie_id'),
    sa.UniqueConstraint('specie_name')
    )
    op.create_table('animals',
    sa.Column('animal_uuid', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.DateTime(), nullable=False),
    sa.Column('short_desc', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('specie_name', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['center.center_id'], ),
    sa.ForeignKeyConstraint(['specie_name'], ['specie.specie_name'], ),
    sa.PrimaryKeyConstraint('animal_uuid'),
    sa.UniqueConstraint('animal_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    op.drop_table('specie')
    op.drop_table('center')
    # ### end Alembic commands ###
